.TH "Junia/src/ECS/Components.h" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Junia/src/ECS/Components.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ECS\&.h'\fP
.br
\fC#include 'PositionComponent\&.h'\fP
.br
\fC#include 'SpriteComponent\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
