.TH "Junia/src/ECS/ECS.h" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Junia/src/ECS/ECS.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponent\fP"
.br
.ti -1c
.RI "class \fBEntity\fP"
.br
.ti -1c
.RI "class \fBManager\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBComponentID\fP = std::size_t"
.br
.ti -1c
.RI "using \fBComponentBitSet\fP = std::bitset< \fBmaxComponents\fP >"
.br
.ti -1c
.RI "using \fBComponentArray\fP = std::array< \fBComponent\fP *, \fBmaxComponents\fP >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBComponentID\fP \fBgetComponentTypeID\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr std::size_t \fBmaxComponents\fP = 32"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBComponentArray\fP =  std::array<\fBComponent\fP*, \fBmaxComponents\fP>"

.SS "using \fBComponentBitSet\fP =  std::bitset<\fBmaxComponents\fP>"

.SS "using \fBComponentID\fP =  std::size_t"

.SH "Function Documentation"
.PP 
.SS "\fBComponentID\fP getComponentTypeID ()\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "constexpr std::size_t maxComponents = 32\fC [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
