.TH "Entity" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "bool \fBisActive\fP ()"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "template<typename T > bool \fBhasComponent\fP () const"
.br
.ti -1c
.RI "template<typename T , typename\&.\&.\&. TArgs> T & \fBaddComponent\fP (TArgs &&\&.\&.\&. mArgs)"
.br
.ti -1c
.RI "template<typename T > T & \fBgetComponent\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename\&.\&.\&. TArgs> T& Entity::addComponent (TArgs &&\&.\&.\&. mArgs)\fC [inline]\fP"

.SS "void Entity::destroy ()\fC [inline]\fP"

.SS "void Entity::draw ()\fC [inline]\fP"

.SS "template<typename T > T& Entity::getComponent () const\fC [inline]\fP"

.SS "template<typename T > bool Entity::hasComponent () const\fC [inline]\fP"

.SS "bool Entity::isActive ()\fC [inline]\fP"

.SS "void Entity::update ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
