.TH "Game" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Game\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGame\fP ()"
.br
.ti -1c
.RI "\fB~Game\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (const char *title, int x, int y, int width, int height, bool fullscreen)"
.br
.RI "initialize the window "
.ti -1c
.RI "void \fBhandleEvents\fP ()"
.br
.RI "handle pending events "
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.RI "update objects, scripts, etc "
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "render what has changed "
.ti -1c
.RI "void \fBclean\fP ()"
.br
.RI "cleanup calls "
.ti -1c
.RI "bool \fBrunning\fP ()"
.br
.RI "check if the application is still running "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static SDL_Renderer * \fBrenderer\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::Game ()"

.SS "Game::~Game ()"

.SH "Member Function Documentation"
.PP 
.SS "void Game::clean ()"

.PP
cleanup calls 
.SS "void Game::handleEvents ()"

.PP
handle pending events 
.SS "void Game::init (const char * title, int x, int y, int width, int height, bool fullscreen)"

.PP
initialize the window 
.PP
\fBParameters\fP
.RS 4
\fItitle\fP window title 
.br
\fIx\fP window position x coordinate 
.br
\fIy\fP window position y coordinate 
.br
\fIwidth\fP the window length along the x axis 
.br
\fIheight\fP the window length along the y axis 
.br
\fIfullscreen\fP if the window should be initialized in fullscreen 
.RE
.PP

.SS "void Game::render ()"

.PP
render what has changed 
.SS "bool Game::running ()\fC [inline]\fP"

.PP
check if the application is still running 
.PP
\fBReturns\fP
.RS 4
true, if the application is running, otherwise false 
.RE
.PP

.SS "void Game::update ()"

.PP
update objects, scripts, etc 
.SH "Member Data Documentation"
.PP 
.SS "SDL_Renderer * Game::renderer = nullptr\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
