.TH "GameObject" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameObject\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameObject\fP (const char *texturesheet, int x, int y)"
.br
.ti -1c
.RI "\fB~GameObject\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameObject::GameObject (const char * texturesheet, int x, int y)"

.SS "GameObject::~GameObject ()"

.SH "Member Function Documentation"
.PP 
.SS "void GameObject::Render ()"

.SS "void GameObject::Update ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
