.TH "Junia/src/main.cpp" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Junia/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Game\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGame\fP * \fBgame\fP = nullptr"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "\fBGame\fP* game = nullptr"

.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
