.TH "Manager" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.ti -1c
.RI "\fBEntity\fP & \fBaddEntity\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBEntity\fP& Manager::addEntity ()\fC [inline]\fP"

.SS "void Manager::draw ()\fC [inline]\fP"

.SS "void Manager::refresh ()\fC [inline]\fP"

.SS "void Manager::update ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
