.TH "Map" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMap\fP ()"
.br
.ti -1c
.RI "\fB~Map\fP ()"
.br
.ti -1c
.RI "void \fBLoadMap\fP (int arr[20][25])"
.br
.ti -1c
.RI "void \fBDrawMap\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Map::Map ()"

.SS "Map::~Map ()"

.SH "Member Function Documentation"
.PP 
.SS "void Map::DrawMap ()"

.SS "void Map::LoadMap (int arr[20][25])"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
