.TH "PositionComponent" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PositionComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PositionComponent\&.h>\fP
.PP
Inherits \fBComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPositionComponent\fP ()"
.br
.ti -1c
.RI "\fBPositionComponent\fP (int \fBx\fP, int \fBy\fP)"
.br
.ti -1c
.RI "int \fBx\fP ()"
.br
.ti -1c
.RI "int \fBy\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP () override"
.br
.ti -1c
.RI "void \fBsetPos\fP (int \fBx\fP, int \fBy\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PositionComponent::PositionComponent ()\fC [inline]\fP"

.SS "PositionComponent::PositionComponent (int x, int y)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PositionComponent::setPos (int x, int y)\fC [inline]\fP"

.SS "void PositionComponent::update ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBComponent\fP\&.
.SS "int PositionComponent::x ()\fC [inline]\fP"

.SS "int PositionComponent::y ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
