.TH "SpriteComponent" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteComponent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpriteComponent\&.h>\fP
.PP
Inherits \fBComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpriteComponent\fP ()=default"
.br
.ti -1c
.RI "\fBSpriteComponent\fP (const char *path)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.ti -1c
.RI "void \fBupdate\fP () override"
.br
.ti -1c
.RI "void \fBdraw\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpriteComponent::SpriteComponent ()\fC [default]\fP"

.SS "SpriteComponent::SpriteComponent (const char * path)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SpriteComponent::draw ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBComponent\fP\&.
.SS "void SpriteComponent::init ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBComponent\fP\&.
.SS "void SpriteComponent::update ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
