.TH "TextureManager" 3 "Sat Nov 13 2021" "Version 0.0.1-preRelease" "Junia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TextureManager\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static SDL_Texture * \fBLoadTexture\fP (const char *filename)"
.br
.ti -1c
.RI "static void \fBDraw\fP (SDL_Texture *tex, SDL_Rect src, SDL_Rect dest)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TextureManager::Draw (SDL_Texture * tex, SDL_Rect src, SDL_Rect dest)\fC [static]\fP"

.SS "SDL_Texture * TextureManager::LoadTexture (const char * filename)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Junia from the source code\&.
