#if JE_WINDOWAPI == JE_WINDOWAPI_WIN32

#include "WindowsInput.hpp"
#include <Junia/Platform/Windows/Win32.hpp>
#include <Junia/Core/KeyCodes.hpp>
#include <Junia/Core/MouseButtonCodes.hpp>
#include <Junia/Core/Log.hpp>

namespace Junia
{
	Input* Input::instance = new WindowsInput();

	unsigned char WindowsInput::JeToWinKey[256] = { };
	unsigned char WindowsInput::WinToJeKey[256] = { };
	unsigned char WindowsInput::WinToJeButton[8] = { };
	unsigned char WindowsInput::JeToWinButton[8] = { };


	void WindowsInput::PopulateConversionArrays()
	{
		JeToWinKey[JE_KEY_HOME] = WIN32_VK_HOME;
		JeToWinKey[JE_KEY_END] = WIN32_VK_END;
		JeToWinKey[JE_KEY_PRINT_SCREEN] = WIN32_VK_SNAPSHOT;
		JeToWinKey[JE_KEY_NUM_LOCK] = WIN32_VK_NUMLOCK;
		JeToWinKey[JE_KEY_CAPS_LOCK] = WIN32_VK_CAPITAL;
		JeToWinKey[JE_KEY_SCROLL_LOCK] = WIN32_VK_SCROLL;
		JeToWinKey[JE_KEY_BACKSPACE] = WIN32_VK_BACK;
		JeToWinKey[JE_KEY_TAB] = WIN32_VK_TAB;
		JeToWinKey[JE_KEY_ENTER] = WIN32_VK_RETURN;
		JeToWinKey[JE_KEY_MENU] = WIN32_VK_EXSEL;
		JeToWinKey[JE_KEY_PAGE_UP] = WIN32_VK_PRIOR;
		JeToWinKey[JE_KEY_PAGE_DOWN] = WIN32_VK_NEXT;
		JeToWinKey[JE_KEY_PAUSE] = WIN32_VK_PAUSE;
		JeToWinKey[JE_KEY_INSERT] = WIN32_VK_INSERT;
		JeToWinKey[JE_KEY_ESCAPE] = WIN32_VK_ESCAPE;
		JeToWinKey[JE_KEY_SPACE] = WIN32_VK_SPACE;
		JeToWinKey[JE_KEY_APOSTROPHE] = WIN32_VK_OEM_7;
		JeToWinKey[JE_KEY_COMMA] = WIN32_VK_OEM_COMMA;
		JeToWinKey[JE_KEY_MINUS] = WIN32_VK_OEM_MINUS;
		JeToWinKey[JE_KEY_PERIOD] = WIN32_VK_OEM_PERIOD;
		JeToWinKey[JE_KEY_SLASH] = WIN32_VK_OEM_2;
		JeToWinKey[JE_KEY_0] = 0x30;
		JeToWinKey[JE_KEY_1] = 0x31;
		JeToWinKey[JE_KEY_2] = 0x32;
		JeToWinKey[JE_KEY_3] = 0x33;
		JeToWinKey[JE_KEY_4] = 0x34;
		JeToWinKey[JE_KEY_5] = 0x35;
		JeToWinKey[JE_KEY_6] = 0x36;
		JeToWinKey[JE_KEY_7] = 0x37;
		JeToWinKey[JE_KEY_8] = 0x38;
		JeToWinKey[JE_KEY_9] = 0x39;
		JeToWinKey[JE_KEY_SEMICOLON] = WIN32_VK_OEM_1;
		JeToWinKey[JE_KEY_EQUAL] = WIN32_VK_OEM_PLUS;
		JeToWinKey[JE_KEY_A] = 0x41;
		JeToWinKey[JE_KEY_B] = 0x42;
		JeToWinKey[JE_KEY_C] = 0x43;
		JeToWinKey[JE_KEY_D] = 0x44;
		JeToWinKey[JE_KEY_E] = 0x45;
		JeToWinKey[JE_KEY_F] = 0x46;
		JeToWinKey[JE_KEY_G] = 0x47;
		JeToWinKey[JE_KEY_H] = 0x48;
		JeToWinKey[JE_KEY_I] = 0x49;
		JeToWinKey[JE_KEY_J] = 0x4A;
		JeToWinKey[JE_KEY_K] = 0x4B;
		JeToWinKey[JE_KEY_L] = 0x4C;
		JeToWinKey[JE_KEY_M] = 0x4D;
		JeToWinKey[JE_KEY_N] = 0x4E;
		JeToWinKey[JE_KEY_O] = 0x4F;
		JeToWinKey[JE_KEY_P] = 0x50;
		JeToWinKey[JE_KEY_Q] = 0x51;
		JeToWinKey[JE_KEY_R] = 0x52;
		JeToWinKey[JE_KEY_S] = 0x53;
		JeToWinKey[JE_KEY_T] = 0x54;
		JeToWinKey[JE_KEY_U] = 0x55;
		JeToWinKey[JE_KEY_V] = 0x56;
		JeToWinKey[JE_KEY_W] = 0x57;
		JeToWinKey[JE_KEY_X] = 0x58;
		JeToWinKey[JE_KEY_Y] = 0x59;
		JeToWinKey[JE_KEY_Z] = 0x5A;
		JeToWinKey[JE_KEY_LEFT_BRACKET] = WIN32_VK_OEM_4;
		JeToWinKey[JE_KEY_BACKSLASH] = WIN32_VK_OEM_5;
		JeToWinKey[JE_KEY_RIGHT_BRACKET] = WIN32_VK_OEM_6;
		//JeToWinKey[JE_KEY_GRAVE_ACCENT] = WIN32_VK_;
		JeToWinKey[JE_KEY_LEFT] = WIN32_VK_LEFT;
		JeToWinKey[JE_KEY_UP] = WIN32_VK_UP;
		JeToWinKey[JE_KEY_RIGHT] = WIN32_VK_RIGHT;
		JeToWinKey[JE_KEY_DOWN] = WIN32_VK_DOWN;
		JeToWinKey[JE_KEY_F1] = WIN32_VK_F1;
		JeToWinKey[JE_KEY_F2] = WIN32_VK_F2;
		JeToWinKey[JE_KEY_F3] = WIN32_VK_F3;
		JeToWinKey[JE_KEY_F4] = WIN32_VK_F4;
		JeToWinKey[JE_KEY_F5] = WIN32_VK_F5;
		JeToWinKey[JE_KEY_F6] = WIN32_VK_F6;
		JeToWinKey[JE_KEY_F7] = WIN32_VK_F7;
		JeToWinKey[JE_KEY_F8] = WIN32_VK_F8;
		JeToWinKey[JE_KEY_F9] = WIN32_VK_F9;
		JeToWinKey[JE_KEY_F10] = WIN32_VK_F10;
		JeToWinKey[JE_KEY_F11] = WIN32_VK_F11;
		JeToWinKey[JE_KEY_F12] = WIN32_VK_F12;
		JeToWinKey[JE_KEY_F13] = WIN32_VK_F13;
		JeToWinKey[JE_KEY_F14] = WIN32_VK_F14;
		JeToWinKey[JE_KEY_F15] = WIN32_VK_F15;
		JeToWinKey[JE_KEY_F16] = WIN32_VK_F16;
		JeToWinKey[JE_KEY_F17] = WIN32_VK_F17;
		JeToWinKey[JE_KEY_F18] = WIN32_VK_F18;
		JeToWinKey[JE_KEY_F19] = WIN32_VK_F19;
		JeToWinKey[JE_KEY_F20] = WIN32_VK_F20;
		JeToWinKey[JE_KEY_F21] = WIN32_VK_F21;
		JeToWinKey[JE_KEY_F22] = WIN32_VK_F22;
		JeToWinKey[JE_KEY_F23] = WIN32_VK_F23;
		JeToWinKey[JE_KEY_F24] = WIN32_VK_F24;
		JeToWinKey[JE_KEY_DELETE] = WIN32_VK_DELETE;
		JeToWinKey[JE_KEY_LEFT_SHIFT] = WIN32_VK_LSHIFT;
		JeToWinKey[JE_KEY_RIGHT_SHIFT] = WIN32_VK_RSHIFT;
		JeToWinKey[JE_KEY_LEFT_CONTROL] = WIN32_VK_LCONTROL;
		JeToWinKey[JE_KEY_RIGHT_CONTROL] = WIN32_VK_RCONTROL;
		JeToWinKey[JE_KEY_LEFT_ALT] = WIN32_VK_LMENU;
		JeToWinKey[JE_KEY_RIGHT_ALT] = WIN32_VK_RMENU;
		JeToWinKey[JE_KEY_LEFT_SUPER] = WIN32_VK_LWIN;
		JeToWinKey[JE_KEY_RIGHT_SUPER] = WIN32_VK_RWIN;
		//JeToWinKey[JE_KEY_KP_ENTER] = WIN32_VK_RETURN; // WRONG
		JeToWinKey[JE_KEY_KP_MULTIPLY] = WIN32_VK_MULTIPLY;
		JeToWinKey[JE_KEY_KP_ADD] = WIN32_VK_ADD;
		JeToWinKey[JE_KEY_KP_SUBTRACT] = WIN32_VK_SUBTRACT;
		JeToWinKey[JE_KEY_KP_DECIMAL] = WIN32_VK_DECIMAL;
		JeToWinKey[JE_KEY_KP_DIVIDE] = WIN32_VK_DIVIDE;
		JeToWinKey[JE_KEY_KP_0] = WIN32_VK_NUMPAD0;
		JeToWinKey[JE_KEY_KP_1] = WIN32_VK_NUMPAD1;
		JeToWinKey[JE_KEY_KP_2] = WIN32_VK_NUMPAD2;
		JeToWinKey[JE_KEY_KP_3] = WIN32_VK_NUMPAD3;
		JeToWinKey[JE_KEY_KP_4] = WIN32_VK_NUMPAD4;
		JeToWinKey[JE_KEY_KP_5] = WIN32_VK_NUMPAD5;
		JeToWinKey[JE_KEY_KP_6] = WIN32_VK_NUMPAD6;
		JeToWinKey[JE_KEY_KP_7] = WIN32_VK_NUMPAD7;
		JeToWinKey[JE_KEY_KP_8] = WIN32_VK_NUMPAD8;
		JeToWinKey[JE_KEY_KP_9] = WIN32_VK_NUMPAD9;
		JeToWinKey[JE_KEY_KP_EQUAL] = WIN32_VK_OEM_PLUS;

		WinToJeKey[WIN32_VK_HOME] = JE_KEY_HOME;
		WinToJeKey[WIN32_VK_END] = JE_KEY_END;
		WinToJeKey[WIN32_VK_SNAPSHOT] = JE_KEY_PRINT_SCREEN;
		WinToJeKey[WIN32_VK_NUMLOCK] = JE_KEY_NUM_LOCK;
		WinToJeKey[WIN32_VK_CAPITAL] = JE_KEY_CAPS_LOCK;
		WinToJeKey[WIN32_VK_SCROLL] = JE_KEY_SCROLL_LOCK;
		WinToJeKey[WIN32_VK_BACK] = JE_KEY_BACKSPACE;
		WinToJeKey[WIN32_VK_TAB] = JE_KEY_TAB;
		WinToJeKey[WIN32_VK_RETURN] = JE_KEY_ENTER;
		WinToJeKey[WIN32_VK_EXSEL] = JE_KEY_MENU;
		WinToJeKey[WIN32_VK_PRIOR] = JE_KEY_PAGE_UP;
		WinToJeKey[WIN32_VK_NEXT] = JE_KEY_PAGE_DOWN;
		WinToJeKey[WIN32_VK_PAUSE] = JE_KEY_PAUSE;
		WinToJeKey[WIN32_VK_INSERT] = JE_KEY_INSERT;
		WinToJeKey[WIN32_VK_ESCAPE] = JE_KEY_ESCAPE;
		WinToJeKey[WIN32_VK_SPACE] = JE_KEY_SPACE;
		WinToJeKey[WIN32_VK_OEM_7] = JE_KEY_APOSTROPHE;
		WinToJeKey[WIN32_VK_OEM_COMMA] = JE_KEY_COMMA;
		WinToJeKey[WIN32_VK_OEM_MINUS] = JE_KEY_MINUS;
		WinToJeKey[WIN32_VK_OEM_PERIOD] = JE_KEY_PERIOD;
		WinToJeKey[WIN32_VK_OEM_2] = JE_KEY_SLASH;
		WinToJeKey[0x30] = JE_KEY_0;
		WinToJeKey[0x31] = JE_KEY_1;
		WinToJeKey[0x32] = JE_KEY_2;
		WinToJeKey[0x33] = JE_KEY_3;
		WinToJeKey[0x34] = JE_KEY_4;
		WinToJeKey[0x35] = JE_KEY_5;
		WinToJeKey[0x36] = JE_KEY_6;
		WinToJeKey[0x37] = JE_KEY_7;
		WinToJeKey[0x38] = JE_KEY_8;
		WinToJeKey[0x39] = JE_KEY_9;
		WinToJeKey[WIN32_VK_OEM_1] = JE_KEY_SEMICOLON;
		WinToJeKey[WIN32_VK_OEM_PLUS] = JE_KEY_EQUAL;
		WinToJeKey[0x41] = JE_KEY_A;
		WinToJeKey[0x42] = JE_KEY_B;
		WinToJeKey[0x43] = JE_KEY_C;
		WinToJeKey[0x44] = JE_KEY_D;
		WinToJeKey[0x45] = JE_KEY_E;
		WinToJeKey[0x46] = JE_KEY_F;
		WinToJeKey[0x47] = JE_KEY_G;
		WinToJeKey[0x48] = JE_KEY_H;
		WinToJeKey[0x49] = JE_KEY_I;
		WinToJeKey[0x4A] = JE_KEY_J;
		WinToJeKey[0x4B] = JE_KEY_K;
		WinToJeKey[0x4C] = JE_KEY_L;
		WinToJeKey[0x4D] = JE_KEY_M;
		WinToJeKey[0x4E] = JE_KEY_N;
		WinToJeKey[0x4F] = JE_KEY_O;
		WinToJeKey[0x50] = JE_KEY_P;
		WinToJeKey[0x51] = JE_KEY_Q;
		WinToJeKey[0x52] = JE_KEY_R;
		WinToJeKey[0x53] = JE_KEY_S;
		WinToJeKey[0x54] = JE_KEY_T;
		WinToJeKey[0x55] = JE_KEY_U;
		WinToJeKey[0x56] = JE_KEY_V;
		WinToJeKey[0x57] = JE_KEY_W;
		WinToJeKey[0x58] = JE_KEY_X;
		WinToJeKey[0x59] = JE_KEY_Y;
		WinToJeKey[0x5A] = JE_KEY_Z;
		WinToJeKey[WIN32_VK_OEM_4] = JE_KEY_LEFT_BRACKET;
		WinToJeKey[WIN32_VK_OEM_5] = JE_KEY_BACKSLASH;
		WinToJeKey[WIN32_VK_OEM_6] = JE_KEY_RIGHT_BRACKET;
		//WinToJeKey[WIN32_VK_] = JE_KEY_GRAVE_ACCENT;
		WinToJeKey[WIN32_VK_LEFT] = JE_KEY_LEFT;
		WinToJeKey[WIN32_VK_UP] = JE_KEY_UP;
		WinToJeKey[WIN32_VK_RIGHT] = JE_KEY_RIGHT;
		WinToJeKey[WIN32_VK_DOWN] = JE_KEY_DOWN;
		WinToJeKey[WIN32_VK_F1] = JE_KEY_F1;
		WinToJeKey[WIN32_VK_F2] = JE_KEY_F2;
		WinToJeKey[WIN32_VK_F3] = JE_KEY_F3;
		WinToJeKey[WIN32_VK_F4] = JE_KEY_F4;
		WinToJeKey[WIN32_VK_F5] = JE_KEY_F5;
		WinToJeKey[WIN32_VK_F6] = JE_KEY_F6;
		WinToJeKey[WIN32_VK_F7] = JE_KEY_F7;
		WinToJeKey[WIN32_VK_F8] = JE_KEY_F8;
		WinToJeKey[WIN32_VK_F9] = JE_KEY_F9;
		WinToJeKey[WIN32_VK_F10] = JE_KEY_F10;
		WinToJeKey[WIN32_VK_F11] = JE_KEY_F11;
		WinToJeKey[WIN32_VK_F12] = JE_KEY_F12;
		WinToJeKey[WIN32_VK_F13] = JE_KEY_F13;
		WinToJeKey[WIN32_VK_F14] = JE_KEY_F14;
		WinToJeKey[WIN32_VK_F15] = JE_KEY_F15;
		WinToJeKey[WIN32_VK_F16] = JE_KEY_F16;
		WinToJeKey[WIN32_VK_F17] = JE_KEY_F17;
		WinToJeKey[WIN32_VK_F18] = JE_KEY_F18;
		WinToJeKey[WIN32_VK_F19] = JE_KEY_F19;
		WinToJeKey[WIN32_VK_F20] = JE_KEY_F20;
		WinToJeKey[WIN32_VK_F21] = JE_KEY_F21;
		WinToJeKey[WIN32_VK_F22] = JE_KEY_F22;
		WinToJeKey[WIN32_VK_F23] = JE_KEY_F23;
		WinToJeKey[WIN32_VK_F24] = JE_KEY_F24;
		WinToJeKey[WIN32_VK_DELETE] = JE_KEY_DELETE;
		WinToJeKey[WIN32_VK_LSHIFT] = JE_KEY_LEFT_SHIFT;
		WinToJeKey[WIN32_VK_RSHIFT] = JE_KEY_RIGHT_SHIFT;
		WinToJeKey[WIN32_VK_LCONTROL] = JE_KEY_LEFT_CONTROL;
		WinToJeKey[WIN32_VK_RCONTROL] = JE_KEY_RIGHT_CONTROL;
		WinToJeKey[WIN32_VK_LMENU] = JE_KEY_LEFT_ALT;
		WinToJeKey[WIN32_VK_RMENU] = JE_KEY_RIGHT_ALT;
		WinToJeKey[WIN32_VK_LWIN] = JE_KEY_LEFT_SUPER;
		WinToJeKey[WIN32_VK_RWIN] = JE_KEY_RIGHT_SUPER;
		//WinToJeKey[WIN32_VK_RETURN] = JE_KEY_KP_ENTER; // WRONG
		WinToJeKey[WIN32_VK_MULTIPLY] = JE_KEY_KP_MULTIPLY;
		WinToJeKey[WIN32_VK_ADD] = JE_KEY_KP_ADD;
		WinToJeKey[WIN32_VK_SUBTRACT] = JE_KEY_KP_SUBTRACT;
		WinToJeKey[WIN32_VK_DECIMAL] = JE_KEY_KP_DECIMAL;
		WinToJeKey[WIN32_VK_DIVIDE] = JE_KEY_KP_DIVIDE;
		WinToJeKey[WIN32_VK_NUMPAD0] = JE_KEY_KP_0;
		WinToJeKey[WIN32_VK_NUMPAD1] = JE_KEY_KP_1;
		WinToJeKey[WIN32_VK_NUMPAD2] = JE_KEY_KP_2;
		WinToJeKey[WIN32_VK_NUMPAD3] = JE_KEY_KP_3;
		WinToJeKey[WIN32_VK_NUMPAD4] = JE_KEY_KP_4;
		WinToJeKey[WIN32_VK_NUMPAD5] = JE_KEY_KP_5;
		WinToJeKey[WIN32_VK_NUMPAD6] = JE_KEY_KP_6;
		WinToJeKey[WIN32_VK_NUMPAD7] = JE_KEY_KP_7;
		WinToJeKey[WIN32_VK_NUMPAD8] = JE_KEY_KP_8;
		WinToJeKey[WIN32_VK_NUMPAD9] = JE_KEY_KP_9;
		//WinToJeKey[WIN32_VK_OEM_PLUS] = JE_KEY_KP_EQUAL; // WRONG


		JeToWinButton[JE_MOUSEBUTTON_LEFT]   = WIN32_VK_LBUTTON;
		JeToWinButton[JE_MOUSEBUTTON_MIDDLE] = WIN32_VK_MBUTTON;
		JeToWinButton[JE_MOUSEBUTTON_RIGHT]  = WIN32_VK_RBUTTON;

		WinToJeButton[WIN32_VK_LBUTTON] =   JE_MOUSEBUTTON_LEFT;
		WinToJeButton[WIN32_VK_MBUTTON] = JE_MOUSEBUTTON_MIDDLE;
		WinToJeButton[WIN32_VK_RBUTTON] =  JE_MOUSEBUTTON_RIGHT;
	}

	bool WindowsInput::IsKeyDownImplementation(int keycode)
	{
		return Win32_GetKeyState(JeToWinKey[keycode]) & 0x8000;
	}

	bool WindowsInput::IsMouseButtonDownImplementation(int button)
	{
		return Win32_GetKeyState(JeToWinButton[button]) & 0x8000;
	}

	std::pair<int, int> WindowsInput::GetMousePositionImplementation()
	{
		Win32_POINT pos;
		Win32_GetCursorPos(&pos);
		return { static_cast<int>(pos.x), static_cast<int>(pos.y) };
	}
}

#endif
